version: '3'
services:
  spider:
    build: .
    volumes:
      - .:/code
    depends_on:
      - elk
  elk:
    image: sebp/elk
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"